In [17]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [18]:
data = np.load('galaxy_catalogue.npy')

In [19]:
df = pd.DataFrame(data)

In [20]:
df.head(10)

u-g      g-r      r-i      i-z       ecc      m4_u      m4_g      m4_r  \
0  1.85765  0.67158  0.42310  0.30610  0.585428  2.251946  2.339849  2.380652   
1  1.74259  0.86085  0.44927  0.28851  0.749812  2.031566  2.084156  2.092272   
2  2.10697  0.96710  0.56810  0.33747  0.630089  1.992887  2.450746  2.473116   
3  1.22840  0.60446  0.39049  0.28913  0.668999  2.056115  2.182252  2.309510   
4  1.80792  0.78124  0.45528  0.35067  0.500170  2.259167  2.194723  2.264567   
5  2.03214  1.07315  0.46602  0.35547  0.572251  2.102820  2.468013  2.450496   
6  2.35909  1.12462  0.66210  0.40878  0.878042  1.839628  1.863597  1.938819   
7  1.51422  0.79143  0.48938  0.41490  0.527915  2.056123  2.055964  2.063201   
8  1.56721  0.89077  0.47569  0.31600  0.738532  2.219361  2.351838  2.361428   
9  1.71180  0.75637  0.35584  0.26032  0.693971  2.365785  2.359929  2.384462   

       m4_i      m4_z  petroR50_u  petroR50_r  petroR50_z  petroR90_u  \
0  2.359738  2.395528    3.095123    3.818919    3.826230    5.174814   
1  2.124075  2.133154    1.430436    1.422533    1.385727    3.732712   
2  2.465324  2.438683    3.099957    3.623704    3.463300    9.110857   
3  2.391414  2.472397    3.627267    4.063471    3.717708    9.580675   
4  2.334713  2.352568    3.256751    3.153533    2.254511    9.206746   
5  2.458613  2.458825   10.772240    3.165609    2.361423   18.450590   
6  2.022217  2.041389    0.822601    1.160667    1.089881    1.381858   
7  2.104309  2.179036   10.086580    9.246612    8.480659   27.275460   
8  2.350443  2.346544    6.974425    4.096219    3.078832   25.192940   
9  2.404375  2.425890    5.513676    4.854186    4.562141   12.925270   

   petroR90_r  petroR90_z   class  
0    8.263009   11.477340  merger  
1    3.416921    3.330347  merger  
2    8.354343   11.265390  merger  
3   12.202420   11.826220  merger  
4    9.790146    6.636931  merger  
5    9.938354    8.612621  merger  
6    2.048602    1.984791  merger  
7   26.458840   25.898560  merger  
8   16.395480   14.574800  merger  
9   11.678700   11.032560  merger

In [21]:
df.tail(10)

u-g      g-r      r-i      i-z       ecc      m4_u      m4_g  \
770  1.48010  0.77873  0.39564  0.27077  0.643722  2.253789  2.495352   
771  1.80617  0.98461  0.46325  0.31555  0.798526  1.802341  2.260056   
772  1.34484  0.56788  0.33240  0.23118  0.582736  2.392035  2.336432   
773  1.19032  0.46183  0.28270  0.17898  0.549975  2.257553  2.272321   
774  1.03384  0.48437  0.34072  0.05186  0.932945  2.181591  2.092876   
775  1.34594  0.64285  0.37813  0.23107  0.779956  2.421518  2.248886   
776  1.19482  0.49611  0.31017  0.16244  0.722125  2.211442  2.294102   
777  1.21489  0.57253  0.35423  0.21312  0.793392  2.264709  2.319192   
778  1.41797  0.86460  0.40020  0.35307  0.835901  2.011354  2.023669   
779  1.49346  0.86623  0.43432  0.31509  0.490623  2.387251  2.529668   

         m4_r      m4_i      m4_z  petroR50_u  petroR50_r  petroR50_z  \
770  2.661496  2.672565  2.558978    4.532952    4.316014    3.559066   
771  2.399299  2.505646  2.561985    3.779945    3.613680    2.963639   
772  2.388582  2.409964  2.432055    5.818589    5.390203    4.603758   
773  2.376743  2.413910  2.419925    5.353786    5.465420    4.628952   
774  2.141803  2.200762  2.237469    4.502631    3.732485    2.916970   
775  2.589488  2.615007  2.601444   13.877220   11.936910   11.337210   
776  2.327795  2.371559  2.358487    3.032364    3.348147    3.062732   
777  2.388157  2.392148  2.384103    4.652165    4.031008    3.122812   
778  2.326873  2.676343  2.560389    5.442954    4.227347    3.774427   
779  2.525753  2.490839  2.487824    5.082120    3.473336    3.107052   

     petroR90_u  petroR90_r  petroR90_z   class  
770    8.073493    9.614533    7.451995  spiral  
771   10.783350    8.244720    6.052660  spiral  
772   12.260130   13.190250   11.016870  spiral  
773    9.466578   11.048320    9.488609  spiral  
774   11.034360    6.967220    5.141307  spiral  
775   32.374710   25.266770   25.934250  spiral  
776    5.833694    8.061935    7.840197  spiral  
777    9.610085    9.280005    6.708179  spiral  
778   16.256520    7.738220    7.865478  spiral  
779    9.206557    8.380891    7.720072  spiral

In [22]:
df = df.sample(frac=1)

In [23]:
df.head()

u-g      g-r      r-i      i-z       ecc      m4_u      m4_g  \
503  2.07089  1.00004  0.43194  0.36183  0.907411  2.269446  2.419222   
773  1.19032  0.46183  0.28270  0.17898  0.549975  2.257553  2.272321   
254  1.27016  0.63787  0.29099  0.23921  0.778688  2.208645  2.497683   
693  1.21336  0.50224  0.25721  0.17268  0.946092  1.951405  2.160169   
166  1.08424  0.55862  0.42537  0.19711  0.410392  1.980685  2.037382   

         m4_r      m4_i      m4_z  petroR50_u  petroR50_r  petroR50_z  \
503  2.430184  2.447101  2.437126    2.939613    3.942823    4.029508   
773  2.376743  2.413910  2.419925    5.353786    5.465420    4.628952   
254  2.507952  2.510103  2.492839    6.332916    5.767449    4.693553   
693  2.315814  2.358128  2.426106    7.260369    6.949909    5.715676   
166  2.102281  2.139429  2.149643    2.785131    2.718468    2.359684   

     petroR90_u  petroR90_r  petroR90_z       class  
503   15.717410   13.120900   13.041800  elliptical  
773    9.466578   11.048320    9.488609      spiral  
254   16.108360   16.495400   13.840490      merger  
693   11.811390   13.444710   10.317080      spiral  
166    5.834107    6.770075    6.072075      merger

In [24]:
df.reset_index(drop=True, inplace=True)

In [25]:
df.head()

u-g      g-r      r-i      i-z       ecc      m4_u      m4_g      m4_r  \
0  2.07089  1.00004  0.43194  0.36183  0.907411  2.269446  2.419222  2.430184   
1  1.19032  0.46183  0.28270  0.17898  0.549975  2.257553  2.272321  2.376743   
2  1.27016  0.63787  0.29099  0.23921  0.778688  2.208645  2.497683  2.507952   
3  1.21336  0.50224  0.25721  0.17268  0.946092  1.951405  2.160169  2.315814   
4  1.08424  0.55862  0.42537  0.19711  0.410392  1.980685  2.037382  2.102281   

       m4_i      m4_z  petroR50_u  petroR50_r  petroR50_z  petroR90_u  \
0  2.447101  2.437126    2.939613    3.942823    4.029508   15.717410   
1  2.413910  2.419925    5.353786    5.465420    4.628952    9.466578   
2  2.510103  2.492839    6.332916    5.767449    4.693553   16.108360   
3  2.358128  2.426106    7.260369    6.949909    5.715676   11.811390   
4  2.139429  2.149643    2.785131    2.718468    2.359684    5.834107   

   petroR90_r  petroR90_z       class  
0   13.120900   13.041800  elliptical  
1   11.048320    9.488609      spiral  
2   16.495400   13.840490      merger  
3   13.444710   10.317080      spiral  
4    6.770075    6.072075      merger

In [26]:
df.describe()

u-g         g-r         r-i         i-z         ecc  \
count  780.000000  780.000000  780.000000  780.000000  780.000000   
mean     1.633556    0.751285    0.390027    0.256630    0.713827   
std      0.680241    0.333986    0.094902    0.434369    0.171010   
min     -8.202350   -4.708600   -0.630590   -7.698340    0.226894   
25%      1.333080    0.620432    0.353687    0.227997    0.592427   
50%      1.701755    0.789610    0.400985    0.294780    0.744386   
75%      1.914082    0.905282    0.430363    0.326920    0.852673   
max     10.624040    1.539170    1.390840    4.879330    0.999812   

              m4_u         m4_g         m4_r         m4_i         m4_z  \
count   780.000000   780.000000   780.000000   780.000000   780.000000   
mean    -36.228336   -10.499354   -23.280043   -36.084795   -48.904677   
std     619.454396   358.104842   506.113635   619.462662   714.833597   
min   -9999.000000 -9999.000000 -9999.000000 -9999.000000 -9999.000000   
25%       2.124926     2.238136     2.303345     2.327275     2.329166   
50%       2.269386     2.351759     2.380019     2.394285     2.390121   
75%       2.390789     2.420319     2.439145     2.448875     2.449683   
max      26.009380     2.724017     2.737767     2.728628     2.730472   

        petroR50_u  petroR50_r   petroR50_z   petroR90_u  petroR90_r  \
count   780.000000  780.000000   780.000000   780.000000  780.000000   
mean    -46.026529    4.897747   -34.147368   -38.642822   12.625589   
std     715.052758    5.647410   619.598004   715.634265    9.482342   
min   -9999.000000    0.617535 -9999.000000 -9999.000000    1.031904   
25%       2.896251    2.884019     2.553682     7.056056    8.101448   
50%       4.391504    3.929862     3.449929    10.743275   10.509180   
75%       6.148377    5.450743     4.832378    14.975497   14.321407   
max      61.133380  134.394700    89.220090   112.493900  162.428100   

        petroR90_z  
count   780.000000  
mean    -27.091879  
std     620.075967  
min   -9999.000000  
25%       7.145191  
50%       9.423079  
75%      13.388955  
max     116.535700

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 780 entries, 0 to 779
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   u-g         780 non-null    float64
 1   g-r         780 non-null    float64
 2   r-i         780 non-null    float64
 3   i-z         780 non-null    float64
 4   ecc         780 non-null    float64
 5   m4_u        780 non-null    float64
 6   m4_g        780 non-null    float64
 7   m4_r        780 non-null    float64
 8   m4_i        780 non-null    float64
 9   m4_z        780 non-null    float64
 10  petroR50_u  780 non-null    float64
 11  petroR50_r  780 non-null    float64
 12  petroR50_z  780 non-null    float64
 13  petroR90_u  780 non-null    float64
 14  petroR90_r  780 non-null    float64
 15  petroR90_z  780 non-null    float64
 16  class       780 non-null    object 
dtypes: float64(16), object(1)
memory usage: 103.7+ KB


In [28]:
df["class"].value_counts(normalize=True) 

merger        0.333333
spiral        0.333333
elliptical    0.333333
Name: class, dtype: float64

In [29]:
df.isna().sum()

u-g           0
g-r           0
r-i           0
i-z           0
ecc           0
m4_u          0
m4_g          0
m4_r          0
m4_i          0
m4_z          0
petroR50_u    0
petroR50_r    0
petroR50_z    0
petroR90_u    0
petroR90_r    0
petroR90_z    0
class         0
dtype: int64

In [30]:
df["conc_u"] = df['petroR50_u']/df['petroR90_u']
df["conc_r"] = df['petroR50_r']/df['petroR90_r']
df["conc_z"] = df['petroR50_z']/df['petroR90_z']

In [31]:
df= df.drop("petroR50_u", axis=1).drop("petroR50_r", axis=1).drop("petroR50_z", axis=1).drop("petroR90_u", axis=1).drop("petroR90_r", axis=1).drop("petroR90_z", axis=1)

In [32]:
df.head()

u-g      g-r      r-i      i-z       ecc      m4_u      m4_g      m4_r  \
0  2.07089  1.00004  0.43194  0.36183  0.907411  2.269446  2.419222  2.430184   
1  1.19032  0.46183  0.28270  0.17898  0.549975  2.257553  2.272321  2.376743   
2  1.27016  0.63787  0.29099  0.23921  0.778688  2.208645  2.497683  2.507952   
3  1.21336  0.50224  0.25721  0.17268  0.946092  1.951405  2.160169  2.315814   
4  1.08424  0.55862  0.42537  0.19711  0.410392  1.980685  2.037382  2.102281   

       m4_i      m4_z       class    conc_u    conc_r    conc_z  
0  2.447101  2.437126  elliptical  0.187029  0.300499  0.308969  
1  2.413910  2.419925      spiral  0.565546  0.494683  0.487843  
2  2.510103  2.492839      merger  0.393145  0.349640  0.339118  
3  2.358128  2.426106      spiral  0.614692  0.516925  0.554001  
4  2.139429  2.149643      merger  0.477388  0.401542  0.388612

In [33]:
Y = df["class"]
X = df.drop("class", axis=1)

In [34]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
Y = label_encoder.fit_transform(Y)

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.72)

## Decision Tree

In [42]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(X_train, Y_train)
Y_preds = clf.predict(X_test)
print(Y_preds[:20])

[2 1 0 2 1 0 0 1 0 0 0 0 1 0 0 2 1 0 2 2]


In [43]:
clf.score(X_test, Y_test)

0.8493150684931506

In [44]:
from sklearn.model_selection import cross_val_score
cv_acc = cross_val_score(clf, X, Y, cv=10, scoring=None)

In [45]:
cv_acc

array([0.83333333, 0.82051282, 0.74358974, 0.82051282, 0.79487179,
       0.84615385, 0.80769231, 0.76923077, 0.79487179, 0.80769231])

In [46]:
cv_acc = np.mean(cv_acc)
cv_acc

0.8038461538461539

## Random Forest

In [56]:
from sklearn.ensemble import RandomForestClassifier 
rfc = RandomForestClassifier()
rfc.fit(X_train, Y_train)
Y_preds = rfc.predict(X_test)
print(Y_preds[:20])

[2 1 0 2 1 0 0 1 0 1 0 0 1 0 0 2 1 0 2 2]


In [58]:
rfc.score(X_test, Y_test)

0.867579908675799

In [59]:
from sklearn.model_selection import cross_val_score
cv_acc = cross_val_score(rfc, X, Y, cv=10, scoring=None)
np.mean(cv_acc)

0.8717948717948719